//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Collections open source project
//
// Copyright (c) 2025 - 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0 WITH Swift-exception
//
//===----------------------------------------------------------------------===//

#if !COLLECTIONS_SINGLE_MODULE
import InternalCollectionsUtilities
import DequeModule
#endif

#if compiler(>=6.4) && UnstableContainersPreview

@available(SwiftStdlib 5.0, *)
extension RigidDeque: Container where Element: ~Copyable {
  @_alwaysEmitIntoClient
  @_lifetime(borrow self)
  public func makeBorrowingIterator(
    from start: Index, to end: Index
  ) -> BorrowingIterator {
    BorrowingIterator(_deque: self, from: start, to: end)
  }

  @_alwaysEmitIntoClient
  public func currentIndex(of iterator: inout BorrowingIterator) -> Index {
    // FIXME: This should validate that the iterator belongs to this deque.
    return iterator._position
  }
}

@available(SwiftStdlib 5.0, *)
extension RigidDeque: BidirectionalContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension RigidDeque: RandomAccessContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension RigidDeque: MutableContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension RigidDeque: RangeReplaceableContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension RigidDeque.SubrangeConsumer: Drain where Element: ~Copyable {
}

@available(SwiftStdlib 5.0, *)
extension RigidDeque where Element: ~Copyable {
  /// Creates a new rigid deque of the specified capacity, populating it with
  /// all items generated by a given producer.
  ///
  /// If the capacity is exhausted before the producer reaches its end, then
  /// this triggers a runtime error.
  ///
  /// If the producer throws an error during this initializer, then all
  /// previously produced items are discarded and the initializer rethrows the
  /// error.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to append to the new
  ///       deque.
  ///
  /// - Complexity: O(`capacity`)
  public init<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    capacity: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    self.init(capacity: capacity)
    try self.append(from: &producer)
  }

  /// Appends at most `newItemCount` items generated by a producer to the end of
  /// this deque.
  ///
  /// If the target deque does not have sufficient capacity to hold the
  /// specified number of new items, then this triggers a runtime error.
  ///
  /// This operation appends as many items as the producer can generate before
  /// either reaching its end (or throwing an error), or filling the specified
  /// capacity. This operation only consumes the first `newItemCount` items in the
  /// producer; if the producer has more, then they remain available after this
  /// method returns.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to append to the deque, or
  ///       nil to use all available capacity.
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(*n*), where *n* is the number of items
  @_alwaysEmitIntoClient
  public mutating func append<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    try self.append(addingCount: newItemCount) { target throws(E) in
      while !target.isFull {
        guard try producer.generate(into: &target) else { break }
      }
    }
  }

  /// Appends all the items generated by a producer to the end of this deque.
  ///
  /// If the target deque does not have sufficient capacity to hold all the
  /// new items, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(*n*), where *n* is the number of items produced.
  @_alwaysEmitIntoClient
  public mutating func append<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    var done = false
    try self.append(
      addingCount: freeCapacity
    ) { target throws(E) in
      while !target.isFull {
        guard try producer.generate(into: &target) else {
          done = true
          break
        }
      }
    }
    if !done {
      done = (try producer.next() == nil)
    }
    precondition(done, "RigidDeque capacity overflow")
  }

  /// Prepends at most `newItemCount` items generated by a producer to the
  /// front of this deque.
  ///
  /// If the target deque does not have sufficient capacity to hold the
  /// specified number of new items, then this triggers a runtime error.
  ///
  /// This operation prepends as many items as the producer can generate before
  /// either reaching its end (or throwing an error), or filling the specified
  /// capacity. This operation only consumes the first `newItemCount` items in
  /// the producer; if the producer has more, then they remain available after
  /// this method returns.
  ///
  /// Note: Partial prepends create a gap in ring buffer storage that needs to
  /// be closed by moving newly prepended items to their correct positions given
  /// the adjusted count. This adds some overhead compared to adding exactly as
  /// many items as promised.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to prepend to the deque, or
  ///       nil to use all available capacity.
  ///    - producer: A producer that generates the items to prepend.
  ///
  /// - Complexity: O(`newItemCount ?? self.freeCapacity`)
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func prepend<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int? = nil,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    try self.prepend(
      addingCount: newItemCount ?? freeCapacity
    ) { target throws(E) in
      try producer.generate(into: &target)
    }
  }

  /// Replaces the specified range of elements by at most `newItemCount` items
  /// generated by a producer.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the capacity of the deque isn't sufficient to accommodate the new
  /// elements, then this method triggers a runtime error.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the items generated by `producer` at `subrange.lowerBound`. This
  /// case is more directly expressed by calling `insert(moving:at:)`.
  ///
  /// Likewise, if the given producer is empty, then this method removes the
  /// elements in the given subrange without replacement. This case is more
  /// directly expressed by calling `removeSubrange`.
  ///
  /// This operation inserts as many items as the producer can generate before
  /// either reaching `newItemCount`, or the producer hitting its end, or
  /// throwing an error. If the producer has more than `newItemCount` items left in
  /// its underlying sequence, then extra items remain available after this
  /// method returns.
  ///
  /// If the operation inserts fewer than `newItemCount` items, then it results in
  /// a gap in ring buffer storage that needs to be closed by moving some
  /// items to their correct positions given the adjusted count. This adds some
  /// overhead compared to adding exactly as many items as promised.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the deque.
  ///   - newItemCount: The maximum number of items to insert into the deque.
  ///   - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(`self.count` + `maxCount`)
  @_alwaysEmitIntoClient
  public mutating func replace<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    addingCount newItemCount: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    try replace(
      removing: subrange,
      addingCount: newItemCount
    ) { target throws(E) in
      while !target.isFull {
        guard try producer.generate(into: &target) else { break }
      }
    }
  }

  /// Inserts at most `newItemCount` items generated by a producer into this
  /// deque, starting at the given index.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the target deque does not have sufficient capacity to hold the
  /// specified number of new items, then this triggers a runtime error.
  ///
  /// This operation inserts as many items as the producer can generate before
  /// either reaching `newItemCount`, or the producer hitting its end, or
  /// throwing an error. If the producer has more than `newItemCount` items
  /// left in its underlying sequence, then extra items remain available after
  /// this method returns.
  ///
  /// If the operation inserts fewer than `newItemCount` items, then it results
  /// in a gap in ring buffer storage that needs to be closed by moving some
  /// items to their correct positions given the adjusted count. This adds some
  /// overhead compared to adding exactly as many items as promised.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to insert into the deque.
  ///    - index: The position at which to insert the new items.
  ///       `index` must be a valid index in the deque.
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(`self.count` + `newItemCount`)
  @_alwaysEmitIntoClient
  public mutating func insert<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int,
    from producer: inout P,
    at index: Int
  ) throws(E)
  where P.Element: ~Copyable
  {
    try insert(addingCount: newItemCount, at: index) { target throws(E) in
      while !target.isFull, try producer.generate(into: &target) {
        // Do nothing
      }
    }
  }
}


@available(SwiftStdlib 5.0, *)
extension RigidDeque /*where Element: Copyable*/ {
  /// Copies the elements of a container and prepends them to the front
  /// of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// container, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(`items.count`)
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & ~Copyable & ~Escapable>(
    copying items: borrowing C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  /// Copies the elements of a container to the front of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// sequence, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(*m*), where *m* is the length of `items`.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & Sequence<Element>>(
    copying items: borrowing C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  /// Copies the elements of a container to the front of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// sequence, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(*m*), where *m* is the length of `items`.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & Collection<Element>>(
    copying items: borrowing C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  @available(SwiftStdlib 6.4, *)
  @inlinable
  package mutating func _insertContainer<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    at index: Int,
    copying items: borrowing C,
    newCount: Int
  ) {
    let expectedCount = self.count + newCount
    var it = items.makeBorrowingIterator()
    insert(addingCount: newCount, at: index) { target in
      it._copyContents(into: &target)
    }
    precondition(
      it.nextSpan().isEmpty && self.count == expectedCount,
      "Broken Container: count doesn't match contents")
  }

  /// Copies the elements of a container into this deque at the specified
  /// position.
  ///
  /// The new elements are inserted before the element currently at the
  /// specified index. If you pass the deque's `endIndex` as the `index`
  /// parameter, then the new elements are appended to the end of the deque.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the capacity of the deque isn't sufficient to accommodate the new
  /// elements, then this method triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to insert into the deque.
  ///    - index: The position at which to insert the new elements. It must be
  ///        a valid index of the deque.
  ///
  /// - Complexity: O(`self.count` + `items.count`).
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func insert<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    copying items: borrowing C, at index: Int
  ) {
    _insertContainer(
      at: index, copying: items, newCount: items.count)
  }

  /// Copies the elements of a container into this deque at the specified
  /// position.
  ///
  /// The new elements are inserted before the element currently at the
  /// specified index. If you pass the deque's `endIndex` as the `index`
  /// parameter, then the new elements are appended to the end of the deque.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the capacity of the deque isn't sufficient to accommodate the new
  /// elements, then this method triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to insert into the deque.
  ///    - index: The position at which to insert the new elements. It must be
  ///        a valid index of the deque.
  ///
  /// - Complexity: O(`self.count` + `items.count`)
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func insert<
    C: Container<Element> & Collection<Element>
  >(
    copying items: borrowing C, at index: Int
  ) {
    _insertContainer(
      at: index, copying: items, newCount: items.count)
  }

  @available(SwiftStdlib 6.4, *)
  @inlinable
  internal mutating func _replace<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    copyingContainer items: borrowing C,
    newCount: Int
  ) {

    let expectedCount = self.count - subrange.count + newCount
    var it = items.makeBorrowingIterator()
    self.replace(removing: subrange, addingCount: newCount) { target in
      it._copyContents(into: &target)
    }
    precondition(
      it.nextSpan().isEmpty && count == expectedCount,
      "Broken Container: count doesn't match contents")
  }

  /// Replaces the specified subrange of elements by copying the elements of
  /// the given container.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the capacity of the deque isn't sufficient to accommodate the new
  /// elements, then this method triggers a runtime error.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the elements of `items` at `subrange.lowerBound`. This case
  /// is more directly expressed by calling `insert(copying:at:)`.
  ///
  /// Likewise, if you pass a zero-length container as the `items`
  /// parameter, this method removes the elements in the given subrange
  /// without replacement. This case is more directly expressed by calling
  /// `removeSubrange`.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the array.
  ///   - items: The new elements to copy into the collection.
  ///
  /// - Complexity: O(`self.count` + `items.count`)
  @available(SwiftStdlib 6.4, *)
  @inlinable
  @inline(__always)
  public mutating func replace<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    copying items: borrowing C
  ) {
    _replace(
      removing: subrange, copyingContainer: items, newCount: items.count)
  }

  /// Replaces the specified subrange of elements by copying the elements of
  /// the given container.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the capacity of the deque isn't sufficient to accommodate the new
  /// elements, then this method triggers a runtime error.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the elements of `items` at `subrange.lowerBound`. This case
  /// is more directly expressed by calling `insert(copying:at:)`.
  ///
  /// Likewise, if you pass a zero-length container as the `items`
  /// parameter, this method removes the elements in the given subrange
  /// without replacement. This case is more directly expressed by calling
  /// `removeSubrange`.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the array.
  ///   - items: The new elements to copy into the collection.
  ///
  /// - Complexity: O(*n* + *m*), where *n* is count of this deque and
  ///   *m* is the count of `items`.
  @available(SwiftStdlib 6.4, *)
  @inlinable
  @inline(__always)
  public mutating func replace<
    C: Container<Element> & Collection<Element>
  >(
    removing subrange: Range<Int>,
    copying items: C
  ) {
    _replace(
      removing: subrange, copyingContainer: items, newCount: items.count)
  }

}

#endif
