//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Collections open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0 WITH Swift-exception
//
//===----------------------------------------------------------------------===//

#if !COLLECTIONS_SINGLE_MODULE
import InternalCollectionsUtilities
import DequeModule
#endif

#if compiler(>=6.4) && UnstableContainersPreview

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: Container where Element: ~Copyable {
  @_alwaysEmitIntoClient
  @_lifetime(borrow self)
  public func makeBorrowingIterator(
    from start: Index, to end: Index
  ) -> BorrowingIterator {
    _storage.makeBorrowingIterator(from: start, to: end)
  }

  @_alwaysEmitIntoClient
  public func currentIndex(of iterator: inout BorrowingIterator) -> Index {
    _storage.currentIndex(of: &iterator)
  }
}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: BidirectionalContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: RandomAccessContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: MutableContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: RangeReplaceableContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque: DynamicContainer where Element: ~Copyable {}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque where Element: ~Copyable {
  /// Appends at most `newItemCount` items generated by a producer to the end of
  /// this deque.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate the specified
  /// number of new elements, then this method reallocates the deque's storage
  /// to grow it, using a geometric growth rate.
  ///
  /// This operation appends as many items as the producer can generate before
  /// either reaching its end (or throwing an error), or filling the specified
  /// capacity. This operation only consumes the first `newItemCount` items in the
  /// producer; if the producer has more, then they remain available after this
  /// method returns.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to append to the deque.
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(*n*) where *n* is the number of new items, when
  ///     amortized over many similar invocations on the same deque.
  @_alwaysEmitIntoClient
  public mutating func append<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    _ensureFreeCapacity(newItemCount)
    try _storage.append(addingCount: newItemCount, from: &producer)
  }

  /// Appends all the items generated by a producer to the end of this deque.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate all the
  /// elements, then this method reallocates the deque's storage
  /// to grow it, using a geometric growth rate.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(*n*) where *n* is the number of new items, when
  ///     amortized over many similarly-sized invocations on the same deque.
  @_alwaysEmitIntoClient
  public mutating func append<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    var done = false
    while !done {
      let c = Swift.max(producer.underestimatedCount, 1)
      try self.append(addingCount: c) { target throws(E) in
        while !target.isFull, !done {
          done = try !producer.generate(into: &target)
        }
      }
    }
  }

  /// Prepends at most `newItemCount` items generated by a producer to the front
  /// of this deque.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate the specified
  /// number of new elements, then this method reallocates the deque's storage
  /// to grow it, using a geometric growth rate.
  ///
  /// This operation prepends as many items as the producer can generate before
  /// either reaching its end (or throwing an error), or filling the specified
  /// capacity. This operation only consumes the first `newItemCount` items in
  /// the producer; if the producer has more, then they remain available after
  /// this method returns.
  ///
  /// Note: Partial prepends create a gap in ring buffer storage that needs to
  /// be closed by moving newly prepended items to their correct positions given
  /// the adjusted count. This adds some overhead compared to adding exactly as
  /// many items as promised.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to prepend to the deque.
  ///    - producer: A producer that generates the items to prepend.
  ///
  /// - Complexity: O(*n*) where *n* is the number of new items, when
  ///     amortized over many similar invocations on the same deque.
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func prepend<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    _ensureFreeCapacity(newItemCount)
    try _storage._handle.uncheckedPrepend(
      addingCount: newItemCount
    ) { target throws(E) in
      while !target.isFull, try producer.generate(into: &target) {
        // Do nothing
      }
    }
  }

  /// Prepends all items generated by a producer to the front of this deque.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate all the
  /// items, then this method reallocates the deque's storage to grow it,
  /// using a geometric growth rate.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to prepend.
  ///
  /// - Complexity: O(*n*) where *n* is the number of new items, when
  ///     amortized over many similarly-sized invocations on the same deque.
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func prepend<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    var done = false
    while !done {
      let c = Swift.max(producer.underestimatedCount, 1)
      _ensureFreeCapacity(c)
      try self.prepend(addingCount: freeCapacity) { target throws(E) in
        while !target.isFull, !done {
          done = try !producer.generate(into: &target)
        }
      }
    }
  }

  /// Creates a new unique deque of the specified capacity, populating it with
  /// all items generated by a given producer.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to append to the new
  ///       deque.
  ///
  /// - Complexity: O(`capacity`)
  public init<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    capacity: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    self.init(minimumCapacity: capacity)
    try self.append(addingCount: capacity, from: &producer)
  }

  /// Creates a new unique deque, populating it with
  /// all items generated by a given producer.
  ///
  /// - Parameters:
  ///    - producer: A producer that generates the items to append to the new
  ///       deque.
  ///
  /// - Complexity: O(`capacity`)
  public init<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    self.init(minimumCapacity: producer.underestimatedCount)
    try self.append(from: &producer)
  }

  /// Inserts at most `newItemCount` items generated by a producer into this
  /// deque, starting at the given index.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the deque does not have sufficient capacity to hold enough items,
  /// then this reallocates the deque's storage to grow its capacity, using a
  /// geometric growth rate.
  ///
  /// This operation inserts as many items as the producer can generate before
  /// either reaching `newItemCount`, or the producer hitting its end, or
  /// throwing an error. If the producer has more than `newItemCount` items
  /// left in its underlying sequence, then extra items remain available after
  /// this method returns.
  ///
  /// If the operation inserts fewer than `newItemCount` items, then it results
  /// in a gap in ring buffer storage that needs to be closed by moving some
  /// items to their correct positions given the adjusted count. This adds some
  /// overhead compared to adding exactly as many items as promised.
  ///
  /// - Parameters:
  ///    - newItemCount: The maximum number of items to insert into the deque.
  ///    - index: The position at which to insert the new items.
  ///       `index` must be a valid index in the deque.
  ///    - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(`self.count` + `newItemCount`) when amortized over many
  ///     similar invocations on the same deque.
  @_alwaysEmitIntoClient
  public mutating func insert<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    addingCount newItemCount: Int,
    from producer: inout P,
    at index: Int
  ) throws(E)
  where P.Element: ~Copyable
  {
    try insert(addingCount: newItemCount, at: index) { target throws(E) in
      while !target.isFull, try producer.generate(into: &target) {
        // Do nothing
      }
    }
  }

  @available(SwiftStdlib 6.4, *)
  @inlinable
  internal mutating func _insertContainer<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    at index: Int,
    copying items: borrowing C,
    newCount: Int
  ) {
    let expectedCount = self.count + newCount
    var it = items.makeBorrowingIterator()
    insert(addingCount: newCount, at: index) { target in
      it._copyContents(into: &target)
    }
    precondition(
      it.nextSpan().isEmpty && count == expectedCount,
      "Broken Container: count doesn't match contents")
  }

  /// Copies the elements of a container into this deque at the specified
  /// position.
  ///
  /// The new elements are inserted before the element currently at the
  /// specified index. If you pass the deque's `endIndex` as the `index`
  /// parameter, then the new elements are appended to the end of the deque.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the deque does not have sufficient capacity to hold enough items,
  /// then this reallocates the deque's storage to grow its capacity, using a
  /// geometric growth rate.
  ///
  /// - Parameters:
  ///    - items: The new elements to insert into the deque.
  ///    - index: The position at which to insert the new elements. It must be
  ///        a valid index of the deque.
  ///
  /// - Complexity: O(`self.count` + `items.count`) when amortized over many
  ///     similar invocations on the same deque.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func insert<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    copying items: borrowing C, at index: Int
  ) {
    _insertContainer(
      at: index, copying: items, newCount: items.count)
  }

  /// Copies the elements of a container into this deque at the specified
  /// position.
  ///
  /// The new elements are inserted before the element currently at the
  /// specified index. If you pass the deque's `endIndex` as the `index`
  /// parameter, then the new elements are appended to the end of the deque.
  ///
  /// Existing elements in the deque's storage are moved as needed to make room
  /// for the new items. (The direction of the move depends on the location of
  /// the insertion, minimizing the cost.)
  ///
  /// If the deque does not have sufficient capacity to hold enough items,
  /// then this reallocates the deque's storage to grow its capacity, using a
  /// geometric growth rate.
  ///
  /// - Parameters:
  ///    - items: The new elements to insert into the deque.
  ///    - index: The position at which to insert the new elements. It must be
  ///        a valid index of the deque.
  ///
  /// - Complexity: O(`self.count` + `items.count`) when amortized over many
  ///     similar invocations on the same deque.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  @inline(__always)
  public mutating func insert<
    C: Container<Element> & Collection<Element>
  >(
    copying items: borrowing C, at index: Int
  ) {
    _insertContainer(
      at: index, copying: items, newCount: items.count)
  }

  /// Replaces the specified range of elements by at most `newItemCount` items
  /// generated by a producer.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate the new
  /// elements, then this method reallocates the deque's storage to grow it,
  /// using a geometric growth rate.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the items generated by `producer` at `subrange.lowerBound`. This
  /// case is more directly expressed by calling `insert(moving:at:)`.
  ///
  /// Likewise, if the given producer is empty, then this method removes the
  /// elements in the given subrange without replacement. This case is more
  /// directly expressed by calling `removeSubrange`.
  ///
  /// This operation inserts as many items as the producer can generate before
  /// either reaching `newItemCount`, or the producer hitting its end, or
  /// throwing an error. If the producer has more than `newItemCount` items left in
  /// its underlying sequence, then extra items remain available after this
  /// method returns.
  ///
  /// If the operation inserts fewer than `newItemCount` items, then it results in
  /// a gap in ring buffer storage that needs to be closed by moving some
  /// items to their correct positions given the adjusted count. This adds some
  /// overhead compared to adding exactly as many items as promised.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the deque.
  ///   - newItemCount: The maximum number of items to insert into the deque.
  ///   - producer: A producer that generates the items to append.
  ///
  /// - Complexity: O(`self.count` + `newItemCount`)
  @_alwaysEmitIntoClient
  public mutating func replace<
    E: Error,
    P: Producer<Element, E> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    addingCount newItemCount: Int,
    from producer: inout P
  ) throws(E)
  where P.Element: ~Copyable
  {
    try replace(removing: subrange, addingCount: newItemCount) { target throws(E) in
      while !target.isFull, try producer.generate(into: &target) {
        // Do nothing
      }
    }
  }
}

@available(SwiftStdlib 5.0, *)
extension UniqueDeque /*where Element: Copyable*/ {
  /// Copies the elements of a container and prepends them to the front
  /// of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// container, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(`items.count`) when amortized over many similar
  ///     invocations on the same deque.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & ~Copyable & ~Escapable>(
    copying items: borrowing C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  /// Copies the elements of a container to the end of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// sequence, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(*m*), where *m* is the length of `items` when amortized
  ///     over many similar invocations on the same deque.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & Sequence<Element>>(
    copying items: borrowing C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  /// Copies the elements of a container to the end of this deque.
  ///
  /// If the deque does not have sufficient capacity to hold all items in the
  /// sequence, then this triggers a runtime error.
  ///
  /// - Parameters:
  ///    - items: The new elements to copy into the deque.
  ///
  /// - Complexity: O(*m*), where *m* is the length of `items` when amortized
  ///     over many similar invocations on the same deque.
  @available(SwiftStdlib 6.4, *)
  @_alwaysEmitIntoClient
  public mutating func prepend<C: Container<Element> & Collection<Element>>(
    copying items: C
  ) {
    self._prepend(copying: items, exactCount: items.count)
  }

  @available(SwiftStdlib 6.4, *)
  @inlinable
  internal mutating func _replace<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    copyingContainer items: borrowing C,
    newCount: Int
  ) {

    let expectedCount = self.count - subrange.count + newCount
    var it = items.makeBorrowingIterator()
    self.replace(removing: subrange, addingCount: newCount) { target in
      it._copyContents(into: &target)
    }
    precondition(
      it.nextSpan().isEmpty && count == expectedCount,
      "Broken Container: count doesn't match contents")
  }

  /// Replaces the specified subrange of elements by copying the elements of
  /// the given container.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate the new
  /// elements, then this method reallocates the deque's storage to grow it,
  /// using a geometric growth rate.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the elements of `items` at `subrange.lowerBound`. This case
  /// is more directly expressed by calling `insert(copying:at:)`.
  ///
  /// Likewise, if you pass a zero-length container as the `items`
  /// parameter, this method removes the elements in the given subrange
  /// without replacement. This case is more directly expressed by calling
  /// `removeSubrange`.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the array.
  ///   - items: The new elements to copy into the collection.
  ///
  /// - Complexity: O(`self.count` + `items.count`)
  @available(SwiftStdlib 6.4, *)
  @inlinable
  @inline(__always)
  public mutating func replace<
    C: Container<Element> & ~Copyable & ~Escapable
  >(
    removing subrange: Range<Int>,
    copying items: borrowing C
  ) {
    _replace(
      removing: subrange, copyingContainer: items, newCount: items.count)
  }

  /// Replaces the specified subrange of elements by copying the elements of
  /// the given container.
  ///
  /// This method has the effect of removing the specified range of elements
  /// from the deque and inserting the new elements starting at the same
  /// location. The number of new elements need not match the number of elements
  /// being removed.
  ///
  /// If the deque doesn't have sufficient capacity to accommodate the new
  /// elements, then this method reallocates the deque's storage to grow it,
  /// using a geometric growth rate.
  ///
  /// If you pass a zero-length range as the `subrange` parameter, this method
  /// inserts the elements of `items` at `subrange.lowerBound`. This case
  /// is more directly expressed by calling `insert(copying:at:)`.
  ///
  /// Likewise, if you pass a zero-length container as the `items`
  /// parameter, this method removes the elements in the given subrange
  /// without replacement. This case is more directly expressed by calling
  /// `removeSubrange`.
  ///
  /// - Parameters:
  ///   - subrange: The subrange of the deque to replace. The bounds of
  ///     the range must be valid indices in the array.
  ///   - items: The new elements to copy into the collection.
  ///
  /// - Complexity: O(*n* + *m*), where *n* is count of this deque and
  ///   *m* is the count of `items`.
  @available(SwiftStdlib 6.4, *)
  @inlinable
  @inline(__always)
  public mutating func replace<
    C: Container<Element> & Collection<Element>
  >(
    removing subrange: Range<Int>,
    copying items: C
  ) {
    _replace(
      removing: subrange, copyingContainer: items, newCount: items.count)
  }
}

#endif
